### ISSUE TITLE
footnote number in page n, footnote text in page n+1

### ISSUE THREAD

**Issue by pelinski** [lewiswolf/personal-latex-template#1]
Hi, 
I came across the following issue: 
for a footnote declared on page n, the text moves to page n+1 while the index remains in the page footer of n. I've attached a screenshot. The issue might be solved by giving the footer more space (i.e. modifying the margins). 

(Cannot really attach the latex files to reproduce since it is a private document)
<img width="679" alt="Screenshot 2022-03-29 at 17 32 08" src="https://user-images.githubusercontent.com/5852181/160661657-a46ea22c-ecb8-4db9-b4e3-ba9e5300a3da.png">

**Comment by lewiswolf** [comment]
Hi Teresa,

So sorry for the delay on this one. Here is the issue resolution: https://github.com/lewiswolf/personal-latex-template/tree/1-footnote-number-in-page-n-footnote-text-in-page-n+1

Let me know that it works for you. Good luck with your upcoming publications!

Best,
Lewis
